//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int IdComment { get; set; }
        public string title { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> mark { get; set; }
        public Nullable<int> idcommunaute { get; set; }
        public Nullable<int> idRecette { get; set; }
    
        public virtual Recette Recette { get; set; }
    }
}
