//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ngCooking_AmnaEntities : DbContext
    {
        public ngCooking_AmnaEntities()
            : base("name=ngCooking_AmnaEntities")
        {
        }
        public ngCooking_AmnaEntities(string strcx)
                : base(strcx)
        {

        }
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Communaute> Communaute { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Recette> Recette { get; set; }
        public virtual DbSet<RecetteIngredient> RecetteIngredient { get; set; }
    }
}
