//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recette()
        {
            this.Comment = new HashSet<Comment>();
            this.RecetteIngredient = new HashSet<RecetteIngredient>();
        }
    
        public int idRecette { get; set; }
        public string name { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public string picture { get; set; }
        public Nullable<int> calories { get; set; }
        public string preparation { get; set; }
        public Nullable<int> idcommunaute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Communaute Communaute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetteIngredient> RecetteIngredient { get; set; }
    }
}
