//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetteIngredient
    {
        public Nullable<int> idRecette { get; set; }
        public Nullable<int> IdIngredient { get; set; }
        public int IdRecetteIngredient { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recette Recette { get; set; }
    }
}
